import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { TaxStoreProvider } from "@/providers/taxStoreProvider";
import Header from "@/components/blocks/Header";

const jakartaSans = localFont({
  src: [
    {
      path: "./fonts/PlusJakartaSans-VariableFont_wght.ttf",
      weight: "400 700",
      style: "normal",
    }
  ],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.className} antialiased bg-slate-100`}
      >
        <Header />
        <TaxStoreProvider>{children}</TaxStoreProvider>
      </body>
    </html>
  );
}
